#!/bin/bash -l
#$ -N cnc_xnat_qa_ANAT
#$ -j y
#$ -pe omp 16
#$ -l mem_per_core=4G
#$ -o /restricted/projectnb/cncxnat/qa/logs/anatqc_$JOB_ID.out
#$ -m ea
#$ -M kkurkela@bu.edu
#$ -P cncxnat
module use /restricted/projectnb/cncxnat/apps/modulefiles/
module load anatqc/openmp-vnav-test
module load freesurfer/8.2.0
OUTDIR=/restricted/projectnb/cncxnat/test/anatqc_vnav_$JOB_ID
BIDSDIR=$OUTDIR/bids
ARTIFACTSDIR=$OUTDIR/artifacts
mkdir -p $BIDSDIR $ARTIFACTSDIR
FS_LICENSE=$(base64 -w 0 "$FREESURFER_HOME/.license")
anatQC.py -v -c /restricted/projectnb/cncxnat/kkurkela/anatqc-vnav.yaml tandem --label $1 --run $2 --bids-dir $BIDSDIR --sub-tasks morph mriqc vnav --fs-license "$FS_LICENSE" --artifacts-dir $ARTIFACTSDIR --xnat-alias xnat2 --openmp 14 --rate-limit 1
